apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  containers:
    - name: kotlincweb
      image: registry.cloud.okteto.net/ktrueda/hello-world:latest
      ports:
        - containerPort: 8080
