apiVersion: v1
kind: Service
metadata:
  name: lb
  labels:
    app: appservice
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: app
